apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: angular-pipeline-run
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: angular-pipeline
  params:
    - name: ANGULAR_APP_IMAGE
      value: "aymeniset/frontend-app"  
    - name: TAG
      value: "latest"  
  workspaces:
    - name: angular-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
