apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: springboot-pipelinerun-1
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: spring-boot-pipeline
  params:
    - name: SPRING_BOOT_IMAGE
      value: aymeniset/backend-sb-app
    - name: TAG
      value: latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
